services:
    web:
        image: reg.lugvitc.net/pwncore:latest
        ports:
            - ${PORT}:8000
        environment:
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            - WORKERS=${WORKERS}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${CONFIG_FILE}:/app/src/pwncore/config.py
        depends_on:
            - db
    db:
        image: postgres:14
        user: ${UID}:${GID}
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ${DATA_PATH}:/var/lib/postgresql/data
        ports:
            - 5432:5432
    admin:
        image: mathesar/mathesar-prod:latest
        ports:
            - ${PORT_ADMIN}:8000
        depends_on:
            - db
