name: Tox

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          "3.11",
          "3.12"
        ]

    steps:
      # TODO: Add caching
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox in Python ${{ matrix.python-version }}
        run: |
          python -m pip install tox-gh
      - name: Run the tox environment (Python ${{ matrix.python-version }})
        run: |
          tox
